---

- name: "[openssh-install] Install OpenSSH Server (RedHat)"
  ansible.builtin.yum:
    name: openssh-server
  when: openssh_server_install

- name: "[openssh-install] Install OpenSSH Client (RedHat)"
  ansible.builtin.yum:
    name: openssh-clients
  when: openssh_client_install
