---

- name: "[openssh-install] Install OpenSSH Server (Debian)"
  ansible.builtin.apt:
    name: openssh-server
  when: openssh_server_install

- name: "[openssh-install] Install OpenSSH Client (Debian)"
  ansible.builtin.apt:
    name: openssh-client
  when: openssh_client_install
