---

- ansible.builtin.include_vars: "{{ ansible_facts['os_family'] }}.yml"

- ansible.builtin.include_tasks: install.deb.yml
  when: ansible_facts['os_family'] == "Debian"
  tags: [openssh, openssh-install]

- ansible.builtin.include_tasks: install.yum.yml
  when: ansible_facts['os_family'] == "RedHat"
  tags: [openssh, openssh-install]

- ansible.builtin.include_tasks: install.portage.yml
  when: ansible_facts['os_family'] == "Gentoo"
  tags: [openssh, openssh-install]

- ansible.builtin.include_tasks: configure.yml
  tags: [openssh, openssh-configure]
